### ISSUE TITLE
opts settings don't work

### ISSUE THREAD

**Issue by tonywarn** [ghostbar/hapi-rethinkdb#2]
Did you try to connect to some other RethinkDB host?
Because option settings doesn't work. It always fall back to localhost.

server.register({
  register: require('hapi-rethinkdb'),
  opts: { url: '111.222.333.444:28015/test' }
 }, function (err) {
  if (err) console.error(err);
});

don't work.

**Comment by ghostbar** [comment]
Try with the protocol in the URL. I'm using it with other hosts in production  and it works

**Comment by ghostbar** [comment]
I know for a fact this is not an issue.
