### ISSUE TITLE
Exposing rethinkdb instance

### ISSUE THREAD

**Issue by natelaws** [ghostbar/hapi-rethinkdb#4]
In the readme it has `request.server.plugins['hapi-rethinkdb'].rethinkdb`.  However in the code it does `plugin.expose('library', rethink);`

Not sure which is actually wanted.

**Comment by ghostbar** [comment]
Ugh, you're right, it should be `rethinkdb`.

**Comment by ghostbar** [comment]
Closed in df46c56adfc09dc634dfe00a1f1616c0a86c3c9d
