### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by gmchaturvedi1** [ghostbar/hapi-rethinkdb#6]
i am using docker installation of rethink db and host and port are 1192.168.99.100 and 32799 when i pass that in opts it is not working .and showing the default one only. kindly suggest as i am new to hapi

**Comment by ghostbar** [comment]
`1192.168.99.100` can't possibly be the IP. Could you please confirm?

Not only that, please share how you are sending the options.

**Comment by henryfjordan** [comment]
The opts variable is for sure not working. It should be `options` instead of the `opts` used in the example registration in the README. See #7
