### ISSUE TITLE
Can't access the RethinkDB context set up by the Hapi plugin.

### ISSUE THREAD

**Issue by ghost** [ghostbar/hapi-rethinkdb#8]
According to the documentation, The RethinkDB library and the connection are bound to the server context inside handlers on  `this.rethinkdb` and `this.rethinkdbConn`.
However, I'm not being able to access those, only using request.server.plugins etc. Is it because the context set inside a plugin with `server.bind()` is only available inside the plugin itself ?

My code is like this: 
index.js

```
const plugins = [{register: require('hapi-rethinkdb'), options: {url: //url here}]

server.register(plugins, () => {
    server.route(require('./routes'))
    server.start()
}) 
```

routes.js:

```
{
   method: 'GET',
   path: '/list-of-things',
   handler: function(request, reply) {

      // I have to use it like this:
      const r = request.server.plugins['hapi-rethinkdb'].rethinkdb;
      const connection = request.server.plugins['hapi-rethinkdb'].connection;

      // Because this throws undefined:
      const r = this.rethinkdb;
      const connection = this.rethinkdbConn
   }

 }
```

Thank you.

**Comment by ghostbar** [comment]
It's really weird; I was checking this (long time without seeing the code) and on index.js L37-40 is making the bind correctly as defined in the documentation :-/

**Comment by ghostbar** [comment]
In other words: I don't know what's wrong. Tomorrow will probably write some tests for this.

**Comment by ghost** [comment]
I was checking the documentation [here](http://hapijs.com/api#serverbindcontext) and it says that 

> When setting context inside a plugin, the context is applied only to methods set up by the plugin.

 Maybe that's why. I'm very new to Hapi js so I don't know much about how plugins work, but perhaps there's a way to bind the library and connect with a shorter syntax. I mean, it's also fine as it is now but it's a bit verbose to make reference to `rethinkdb` and `connection` like I mentioned.

**Comment by ghostbar** [comment]
You can always import all this to a single file, and make it so that file exports them. Remember when you make an assignation on javascript is just a reference and it's cached because of node, so:

```
var myModule = {}
function setup (server) {
  myModule = {
    r: server.plugins['hapi-rethinkdb'].rethinkdb,
    connection: server.plugins['hapi-rethinkdb'].connection
  }
}
module.exports = myModule
module.exports.setup = setup
```

So, you call setup where you have `server` available and then just import `myModule` and you will have there your references to the plugin.
